/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierFinanceManagerRole;

import UserInterface.AmazonFinanceManagerRole.*;
import Business.EcoSystem;
import Business.FinancialAccount.AmazonFinancialAccount;
import Business.FinancialAccount.SupplierFinancialAccount;
import Business.Invoice.Invoice;
import Business.Organization.AmazonFinanceOrganization;
import Business.Organization.Organization;
import Business.Organization.SupplierFinanceOrganization;
import Business.Payment.Payment;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sony
 */
public class ViewSupplierBankAccountJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private JPanel userProcessContainer;
    /**
     * Creates new form ViewBankAccountJPanel
     */
    public ViewSupplierBankAccountJPanel(EcoSystem system, JPanel userProcessContainer) {
        initComponents();
        this.system = system;
                this.userProcessContainer= userProcessContainer;
        populateTable();
    }
    
 public void populateTable(){
    SupplierFinanceOrganization sfo = null;
    DefaultTableModel model = (DefaultTableModel) bankAccountJTable.getModel();
         model.setRowCount(0);
        for (Organization organization1 : system.getOrganizationDirectory().getOrganizationList()) {
            if (organization1 instanceof SupplierFinanceOrganization) {
                sfo = (SupplierFinanceOrganization) organization1;
       // ArrayList<Payment> paymentList = sfo.getPh().getPaymentList();
     /*   for(Payment payment : sfo.getPh().getPaymentList()){
            
            AmazonFinancialAccount afa = payment.getAmazonFinancialAccount();
                    
            Object[] orderRow = new Object[3];
            orderRow[0] = AmazonFinancialAccount.AccountName;            
            orderRow[1] = AmazonFinancialAccount.AccountNumber;
            orderRow[2] = afa.getAccountValue();
           
            ((DefaultTableModel) bankAccountJTable.getModel()).addRow(orderRow);
        
    } */
                SupplierFinancialAccount sfa = sfo.getSupplierFinancialAccount();
                    
            Object[] orderRow = new Object[3];
            orderRow[0] = AmazonFinancialAccount.AccountName;            
            orderRow[1] = AmazonFinancialAccount.AccountNumber;
            orderRow[2] = sfa.getAccountValue();
           
            ((DefaultTableModel) bankAccountJTable.getModel()).addRow(orderRow);
        
                
            }
        }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bankAccountJTable = new javax.swing.JTable();

        bankAccountJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Bank Account Name", "Bank Account No.", "Available Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bankAccountJTable);
        bankAccountJTable.getColumnModel().getColumn(0).setResizable(false);
        bankAccountJTable.getColumnModel().getColumn(1).setResizable(false);
        bankAccountJTable.getColumnModel().getColumn(2).setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bankAccountJTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
