/*
 * CreateProductJPanel.java
 *
 * Created on September 18, 2008, 2:54 PM
 */
package UserInterface.InventoryManagerRole;

import Business.ProductCatalog.Product;
import Business.ProductCatalog.ProductCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 *
 */
public class CreateNewProductJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    ProductCatalog productCatalog;
    
    /** Creates new form CreateProductJPanel */
    public CreateNewProductJPanel(JPanel userProcessContainer, ProductCatalog productCatalog){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.productCatalog = productCatalog;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nameField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        proSpJTextArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        availabiltyField1 = new javax.swing.JTextField();
        pCatJComboBox = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create New Product");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Product Price:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 180, 110, 30));

        priceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 210, 30));

        createButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createButton.setText("Add Product");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        backButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Product Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 30));

        nameField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nameField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 210, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Availabilty :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Product Catagory:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 30));

        proSpJTextArea.setColumns(20);
        proSpJTextArea.setRows(5);
        jScrollPane1.setViewportView(proSpJTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 230, 80));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Product Specifications:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 30));

        availabiltyField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(availabiltyField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 210, 30));

        pCatJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Books and Audible", "Movies, Music & Games", "Electronics and Computers", "Home, Garden & Tools", "Beauty, Health & Grocery", "Toy, Kids & Babies", "Clothing, Shoes & Jewelry", "Sports & Outdoors", "Automotive & Industrial" }));
        add(pCatJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 230, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
    // TODO add your handling code here:
     Product product = productCatalog.newProduct();
     
     product.setName(nameField1.getText());
     product.setSellingPrice(Float.parseFloat(priceField.getText()));
     product.setAvailability(Integer.parseInt(availabiltyField1.getText()));
     product.setProductSpecifications(proSpJTextArea.getText());
     //product.setProductCategory(productCatagoryJField.getText());
     product.setProductCategory(String.valueOf(pCatJComboBox.getSelectedItem()));
}//GEN-LAST:event_createButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton1ActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availabiltyField1;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField1;
    private javax.swing.JComboBox pCatJComboBox;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextArea proSpJTextArea;
    // End of variables declaration//GEN-END:variables
}
