/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CustomerManagementOrganization;
import Business.Organization.Organization;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sony
 */
public class CustomerSignUpJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    /**
     * Creates new form CustomerSignUpJPanel
     */
    public CustomerSignUpJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastNamejTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ssnJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        signUpjButton = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jRetypePasswordField2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        ageJTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 18))); // NOI18N
        setLayout(null);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("New to Amazon.com? Register Below.");

        jLabel2.setText("My First Name is :");

        jLabel3.setText("My Last Name is :");

        jLabel4.setText("My SSN is :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Protect Your Information with a Password.");

        jLabel6.setText("Username :");

        jLabel7.setText("Password :");

        signUpjButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        signUpjButton.setText("Sign Up");
        signUpjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpjButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Re-type Password :");

        jLabel8.setText("My Age is :");

        jLabel10.setText("years");

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNamejTextField)
                            .addComponent(lastNamejTextField)
                            .addComponent(ssnJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(usernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jRetypePasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(208, 208, 208)))
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(signUpjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(usernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ssnJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jRetypePasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpjButton)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        add(jPanel1);
        jPanel1.setBounds(16, 35, 814, 320);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpjButtonActionPerformed
        // TODO add your handling code here:
        
        if ("".equals(usernameJTextField.getText()) || ("".equals(String.valueOf(jPasswordField.getPassword()))) || ("".equals(String.valueOf(jRetypePasswordField2.getPassword())))
                || "".equals(firstNamejTextField.getText()) || "".equals(lastNamejTextField.getText()) || "".equals(ageJTextField.getText()) || "".equals(ssnJTextField.getText())) {

            JOptionPane.showMessageDialog(null, "Please enter proper details");
            return;
        } else {
            String uname = usernameJTextField.getText();
            char[] passwordCharArray = jPasswordField.getPassword();
            String pass = String.valueOf(passwordCharArray);
            char[] passwordCharArray1 = jRetypePasswordField2.getPassword();
            String rePass = String.valueOf(passwordCharArray1);
            String firstname = firstNamejTextField.getText();
            
            int ssnEntered = Integer.valueOf(ssnJTextField.getText());
            String fname = firstNamejTextField.getText();
            String lname = lastNamejTextField.getText();
            int ageEntered = Integer.valueOf(ageJTextField.getText());
            try{
               Integer.parseInt(ageJTextField.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Invalid Value! Enter Correct Value");
                return;
            }
            try{
                Integer.parseInt(ssnJTextField.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Invalid Value! Enter Correct Value");
                return;
            }
            
            

            CustomerManagementOrganization org = null;
            for (Organization organization : system.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof CustomerManagementOrganization) {
                    org = (CustomerManagementOrganization) organization;
                    //Customer customer= org.getCd().searchPerson(firstname,ssn);
                    boolean checkssn = org.getCd().checkForSsn(ssnEntered);
                   // boolean reply = org.getUserAccountDirectory().searchUser(uname);

                     
                    
        UserAccount userAccount = null;
        
        Organization inOrganization = null;
         
        userAccount = system.getUserAccountDirectory().searchForUser(uname);
        if(userAccount== null){        
            for(Organization organization2 : system.getOrganizationDirectory().getOrganizationList()){
                userAccount = organization2.getUserAccountDirectory().searchForUser(uname);                
                if(userAccount!= null){                    
                    JOptionPane.showMessageDialog(null, "1Username already exists!! Select a new Username and try again");
                    return;
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "2Username already exists!! Select a new Username and try again");
            return;
        }
        
              
        if (userAccount == null) {
            Network network = system.getNetwork();
            OUTERMOST: for(Network country : network.getNetworkList()) {
                for (Network state : country.getNetworkList()) {
                    for (Network city : state.getNetworkList()) {
                        for (Enterprise enterprise : city.getEnterpriseDirectory().getEnterpriseList()) {
                            
                            userAccount = enterprise.getUserAccountDirectory().searchForUser(uname);
                            System.err.println(userAccount);

                            if (userAccount != null) {
                                JOptionPane.showMessageDialog(null, "3Username already exists!! Select a new Username and try again");
                                break OUTERMOST;
                            } else {

                                for (Organization organization1 : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                    System.err.println("Hello");
                                    userAccount = organization1.getUserAccountDirectory().searchForUser(uname);

                                    if (userAccount != null) {
                                        JOptionPane.showMessageDialog(null, "4Username already exists!! Select a new Username and try again");
                                        break OUTERMOST;
                                    }
                                }
                            }
//                            if (userAccount != null) {
//                                break;
//                            }
                        }
//                        if (userAccount != null) {
//                            break;
//                        }
                    }
//                    if (userAccount != null) {
//                        break;
//                    }
                }
//                if (userAccount != null) {
//                    break;
//                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "5Username already exists!! Select a new Username and try again");
            return;
        }
                    
        
                    if (rePass.equals(pass)) {
                        if (checkssn == true) {

                            if (userAccount == null) {
                                Customer customer = org.getCd().newCustomer(fname, lname, Integer.valueOf(ssnEntered), ageEntered);
                                UserAccount ua = org.getUserAccountDirectory().createUserAccountForCustomer(uname, pass, customer, new CustomerRole());
                                JOptionPane.showMessageDialog(null, "Congratulation!! Your Account is now created!! Login with your details");
                            } 
                        } else {
                            JOptionPane.showMessageDialog(null, "SSN is not unique!! Please enter correct details");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Passwords doesnt match!!! Retry");
                    }
                }

            }
        }
       
       
       
       
       /*   if("".equals(firstNamejTextField.getText())||"".equals(lastNamejTextField.getText())|| "".equals(ageJTextField.getText()) || "".equals(ssnJTextField.getText()))
        {
            JOptionPane.showMessageDialog(null, "Please enter proper details");
            return;
        }
        
        
        int ssnEntered = Integer.parseInt(ssnJTextField.getText());
        String fname = firstNamejTextField.getText();
        String lname = lastNamejTextField.getText();
        int ageEntered = Integer.parseInt(ageJTextField.getText());
        
        
        
            CustomerManagementOrganization org = null;
            for (Organization organization : system.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof CustomerManagementOrganization) {
                      org = (CustomerManagementOrganization) organization;
                           boolean checkssn = org.getCd().checkForSsn(ssnEntered);
                           
                            if(checkssn == true){
                   
                   Customer customer = org.getCd().newCustomer(fname,lname,ssnEntered, ageEntered);
                   usernameJTextField.setEnabled(true);
                   jPasswordField.setEnabled(true);
                   jRetypePasswordField2.setEnabled(true);
                   firstNamejTextField.setEditable(false);
                   lastNamejTextField.setEditable(false);
                   ssnJTextField.setEditable(false);
                   ageJTextField.setEditable(false);
                   signUpjButton.setEnabled(true);
                   
                   
               }else{
                   JOptionPane.showMessageDialog(null, "SSN is not unique!! Please enter correct details");
               }
                      
                }
            }
                                       
        
                   */
       
       
    }//GEN-LAST:event_signUpjButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField firstNamejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jRetypePasswordField2;
    private javax.swing.JTextField lastNamejTextField;
    private javax.swing.JButton signUpjButton;
    private javax.swing.JTextField ssnJTextField;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
