/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.ConfigureASystem;
import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.AmazonFinanceOrganization;
import Business.Organization.AmazonOrderManagementOrganization;
import Business.Organization.CustomerManagementOrganization;
import Business.Organization.Organization;
import Business.Organization.SystemAdminOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    private DB4OUtil db4oUtil = DB4OUtil.getInstance();

    public MainJFrame() {
        initComponents();
        //system = ConfigureASystem.configure();
        system = db4oUtil.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        loginJButton = new javax.swing.JButton();
        userNameJTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        signUpJButton = new javax.swing.JButton();
        signUpSupJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        checkReqJButton = new javax.swing.JButton();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);

        loginJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/account-icon.jpg"))); // NOI18N
        loginJButton.setText("Login");
        loginJButton.setToolTipText("");
        loginJButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("UserName");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Password");

        logoutJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutJButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\sony\\Downloads\\Sign-Stop-icon.png")); // NOI18N
        logoutJButton.setText("LogOut");
        logoutJButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("New User ???");

        signUpJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signUpJButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\sony\\Downloads\\user-info-icon.png")); // NOI18N
        signUpJButton.setText("Sign Up");
        signUpJButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        signUpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpJButtonActionPerformed(evt);
            }
        });

        signUpSupJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signUpSupJButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\sony\\Downloads\\user-info-icon.png")); // NOI18N
        signUpSupJButton.setText("Sign Up Supplier");
        signUpSupJButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        signUpSupJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpSupJButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Supplier Registration ???");

        checkReqJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkReqJButton.setText("Check Request Status");
        checkReqJButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        checkReqJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkReqJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(loginJLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(userNameJTextField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(checkReqJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signUpJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(signUpSupJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(signUpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(signUpSupJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkReqJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        container.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // Get user name
        UserAccount userAccount = null;
        String userName = userNameJTextField.getText();
        // Get Password
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the EcoSystem
       
         //Step2: If user account is not in the system's user account directory
        userAccount = system.authenticateUser(userName, password);
        if(userAccount == null){
        SystemAdminOrganization org = null;
        //CustomerManagementOrganization cmo = null;
        for(Organization organization : system.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof SystemAdminOrganization) {
        org = (SystemAdminOrganization) organization;
        userAccount = org.authenticateUser(userName, password); 
        
          }
        }
        }
        if (userAccount == null){
        CustomerManagementOrganization cmo = null;
        for(Organization organization : system.getOrganizationDirectory().getOrganizationList()){
        if (organization instanceof CustomerManagementOrganization){
        cmo = (CustomerManagementOrganization) organization;
        
        userAccount = cmo.authenticateUser(userName, password);
        }
        }
        
        }
        if (userAccount == null){
        AmazonOrderManagementOrganization aomo = null;
            for (Organization organization : system.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof AmazonOrderManagementOrganization) {
                      aomo = (AmazonOrderManagementOrganization) organization;
                      userAccount = aomo.authenticateUser(userName, password);
                }
            }
        
        }
        if (userAccount == null){
        AmazonFinanceOrganization afo = null;
            for (Organization organization : system.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof AmazonFinanceOrganization) {
                      afo = (AmazonFinanceOrganization) organization;
                      userAccount = afo.authenticateUser(userName, password);
                      
                      
                }
            }
        
        }
         
         
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
         
        
        if (userAccount == null) {
            Network network = system.getNetwork();
            for (Network country : network.getNetworkList()) {
                for (Network state : country.getNetworkList()) {
                    for (Network city : state.getNetworkList()) {
                        for (Enterprise enterprise : city.getEnterpriseDirectory().getEnterpriseList()) {

                            userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);


                            if (userAccount != null) {
                                inEnterprise = enterprise;
                                break;
                            } else {

                                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                    System.err.println("Hello");
                                    userAccount = organization.authenticateUser(userName, password);

                                    if (userAccount != null) {
                                        inEnterprise = enterprise;
                                        inOrganization = organization;
                                        break;
                                    }
                                }
                            }
                            if (inOrganization != null) {
                                break;
                            }
                        }
                        if (inEnterprise != null) {
                            break;
                        }
                    }
                    if (inEnterprise != null) {
                        break;
                    }
                }
                if (inEnterprise != null) {
                    break;
                }
            }
        }

        

        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid Credentials!");
        } else {
            CardLayout layout = (CardLayout) container.getLayout();
            container.add("workArea", userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, system));
            layout.next(container);
        }

        


    }//GEN-LAST:event_loginJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        container.add(new JPanel());
        ((CardLayout)container.getLayout()).next(container);
        System.out.println(system);
        db4oUtil.storeSystem(system);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void signUpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpJButtonActionPerformed
        // TODO add your handling code here:
        
        CardLayout layout = (CardLayout) container.getLayout();
        CustomerSignUpJPanel signUpJPanel = new CustomerSignUpJPanel(container, system);
        container.add("SignUpJPanel", signUpJPanel);
        layout.next(container);
                          
    }//GEN-LAST:event_signUpJButtonActionPerformed

    private void signUpSupJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpSupJButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        SupplierSignUpJPanel ssujp= new SupplierSignUpJPanel(container, system);
        container.add("SupplierSignUpJPanel", ssujp);
        layout.next(container);
    }//GEN-LAST:event_signUpSupJButtonActionPerformed

    private void checkReqJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkReqJButtonActionPerformed
        // TODO add your handling code here:
        
        CardLayout layout = (CardLayout) container.getLayout();
        CheckStatusJPanel csjp= new CheckStatusJPanel( system,container);
        container.add("CheckStatusJPanel", csjp);
        layout.next(container);
    }//GEN-LAST:event_checkReqJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkReqJButton;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signUpJButton;
    private javax.swing.JButton signUpSupJButton;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
