/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierOrderManagerRole;


import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Organization.AmazonOrderManagementOrganization;
import Business.Organization.DeliveryManagementOrganization;
import Business.Organization.Organization;
import Business.Organization.PackagingOrganization;
import Business.Organization.SupplierOrderManagementOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AmazonOrderProcessRequest;
import Business.WorkQueue.DeliveryRequest;
import Business.WorkQueue.PackagingRequest;
import Business.WorkQueue.SupplierOrderRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ViewOrderDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SupplierOrderRequest request;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private UserAccount account;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ViewOrderDetailsJPanel(JPanel userProcessContainer, EcoSystem system ,UserAccount account,SupplierOrderRequest request, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.request = request;
        this.enterprise = enterprise;
        this.system = system;
        this.account = account;
        
        refresh();
    }

    public void refresh() {
        DefaultTableModel dff = (DefaultTableModel) orderjTable.getModel();
        dff.setRowCount(0);

        AmazonOrderManagementOrganization aomo = null;
        for (Organization org : system.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof AmazonOrderManagementOrganization) {
                aomo = (AmazonOrderManagementOrganization) org;


                for (Order o : aomo.getMasterOrderList().getOrdersByCustomer(request.getCustomer())) {
                    if(request.getFinalOrder().getOrderId()== o.getOrderId()){
                    for (OrderItem item : o.getOrderItemList()) {
                        
                        Object[] orderRow = new Object[4];
                        orderRow[0] = item;
                        orderRow[1] = item.getProduct().getSellingPrice();
                        orderRow[2] = (item.getProduct().getAvailability()+request.getQuantity());
                        orderRow[3] = request.getResult();

                        dff.addRow(orderRow);
                    }
                    }
                
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderjTable = new javax.swing.JTable();

        submitJButton.setText("Submit Order to Packaging Department");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        orderjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Price", "Availability", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderjTable);
        orderjTable.getColumnModel().getColumn(0).setResizable(false);
        orderjTable.getColumnModel().getColumn(1).setResizable(false);
        orderjTable.getColumnModel().getColumn(3).setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(submitJButton))
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        
        
        int selectedRow = orderjTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a Row First");
            return;
        }


        OrderItem item = (OrderItem) orderjTable.getValueAt(selectedRow, 0);
        Enterprise e = item.getEnterprise();
        PackagingOrganization pmo = null;
        for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof PackagingOrganization) {
                pmo = (PackagingOrganization) org;



                PackagingRequest packRequest = new PackagingRequest();
                packRequest.setSender(account);
                packRequest.setRequestDate(request.getRequestDate());
                packRequest.setProductId(item.getProduct().getProductId());
                packRequest.setQuantity(item.getQuantity());
                packRequest.setCustomer(request.getCustomer());
                packRequest.setStatus("Order Verified,Prepare for Packing");
                packRequest.setResult("Incomplete");
                packRequest.setProductName(item.getProduct().getName());


                pmo.getWorkQueue().getWorkRequestList().add(packRequest);
                account.getWorkQueue().getWorkRequestList().add(packRequest);
                JOptionPane.showMessageDialog(null, "Your order is sent to Packaging Department !!!");
            }
        }

        request.setResult("Completed");
        request.setStatus("Order Sent to Packaging");
        
        
                                
    }//GEN-LAST:event_submitJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderjTable;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
