/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Invoice.Invoice;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Payment.Payment;
import Business.Payment.PaymentHistory;
import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.Collator;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * 
 */
public class CheckoutJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewParticularInvoiceJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount account;
    private Order tempOrder;
    private Organization organization;
    private Invoice tempInvoice;
    private Customer customerPerson;
    //private PaymentHistory paymentHistory;
    
    public CheckoutJPanel(JPanel userProcessContainer,Order tempOrder, Customer customerPerson, UserAccount account ,Organization organization, EcoSystem system){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        this.tempOrder = tempOrder;
        this.tempInvoice = new Invoice();
        this.organization = organization;
        this.customerPerson = customerPerson;
        tempInvoice.setOrder(tempOrder);
        totalValuejTextField.setText(String.valueOf(tempOrder.getTotalValueOfOrder()));

        refresh();
    }

     public void refresh() {
            DefaultTableModel dff = (DefaultTableModel) orderjTable.getModel();
            dff.setRowCount(0);

        for (OrderItem item : tempOrder.getOrderItemList()) {
            
            Object[] orderRow = new Object[5];
            orderRow[0] = item.getProduct().getProductId();            
            orderRow[1] = item;
            orderRow[2] = item.getQuantity();
            orderRow[3] = item.getProduct().getSellingPrice();
            orderRow[4] = item.getEnterprise();
                    
            dff.addRow(orderRow);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backjButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderjTable = new javax.swing.JTable();
        refreshjButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        totalValuejTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        taxjTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tivjTextField = new javax.swing.JTextField();
        estimateSalesJButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        checkTimeJButton = new javax.swing.JButton();
        payJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Order Details :-");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 23, 89, 20));

        backjButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        backjButton2.setText("<<Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });
        add(backjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        orderjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Quantity", "Price", "Supplier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderjTable);

        refreshjButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        refreshjButton1.setText("Refresh");
        refreshjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total Value of Order:-");

        totalValuejTextField.setEditable(false);
        totalValuejTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tax:-");

        taxjTextField.setEditable(false);
        taxjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Total Invoice Value:-");

        tivjTextField.setEditable(false);
        tivjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        estimateSalesJButton.setText("Estimate Sales :");
        estimateSalesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimateSalesJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel5)
                            .add(jLabel10)
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(taxjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tivjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(totalValuejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(77, 77, 77)
                                .add(estimateSalesJButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(refreshjButton1))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 665, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(4, 4, 4)
                .add(refreshjButton1)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(estimateSalesJButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel5)
                        .add(totalValuejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(taxjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(tivjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 710, -1));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel18.setFont(new java.awt.Font("Cambria", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("Want Same Day Delievery??? ");

        jLabel20.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel20.setText("Check if it is applicable on your order or not !");

        checkTimeJButton.setText("CHECK");
        checkTimeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTimeJButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(62, 62, 62)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel20)
                            .add(jLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 319, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(167, 167, 167)
                        .add(checkTimeJButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(jLabel18)
                .add(29, 29, 29)
                .add(jLabel20)
                .add(47, 47, 47)
                .add(checkTimeJButton)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 710, 240));

        payJButton.setText("Proceed to Payment >>");
        payJButton.setEnabled(false);
        payJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payJButtonActionPerformed(evt);
            }
        });
        add(payJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton2ActionPerformed

    private void refreshjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButton1ActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_refreshjButton1ActionPerformed

    private void estimateSalesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimateSalesJButtonActionPerformed
        // TODO add your handling code here:
        
        float orderValue = tempOrder.getTaxValue();
        taxjTextField.setText(String.valueOf(orderValue));
        float finalamount = tempOrder.getTotalValueOfOrder()+ orderValue;
        tempOrder.setFinalAmount(finalamount);
        tempInvoice.setTotalInvoiceAmount(tempOrder.getFinalAmount());
        tivjTextField.setText(String.valueOf(tempInvoice.getTotalInvoiceAmount()));
        
        payJButton.setEnabled(true);
        //populateSalesTax();
    }//GEN-LAST:event_estimateSalesJButtonActionPerformed

    private void checkTimeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTimeJButtonActionPerformed
        // TODO add your handling code here:
        
 //        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
//         //get current date time with Date()
//         Date date = new Date();
//         String dateString = dateFormat.format(date);
//         
//         Date systemDate = dateFormat.parse("13:00:00");
//         if(dateString> dateFormat.format(systemDate)){}
//         
        
  //      SimpleDateFormat parser = new SimpleDateFormat("HH:mm");
//       DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
//	   
//	   Date date = new Date();
//	   System.out.println(dateFormat.format(date));
//           Calendar cal = Calendar.getInstance();
//	   System.out.println(dateFormat.format(cal.getTime()));
//           
     
        
 /* SimpleDateFormat parser = new SimpleDateFormat("HH:mm:ss");
  
    Date sixteen = parser.parse("16:00:00");

try {
   Calendar cal2 = Calendar.getInstance();
  
   String time = String.valueOf(parser.format(cal2.getTime()));
    System.err.println(parser.format(cal2.getTime()));
    Date userDate = parser.parse(time);
    if (userDate.before(sixteen)) {
        System.err.println("Same Day Delivery is applicable for your order");
    }
    else{
    System.err.println("Same Day Delivery is not applicable for your order!");
    }
} catch (ParseException e) {
    System.err.println("No you ain't set");
}
            */
            
       
        Calendar calendar = new GregorianCalendar();
	    String am_pm;
	    int hour = calendar.get(Calendar.HOUR);
	    int minute = calendar.get(Calendar.MINUTE);
	  //  int second = calendar.get(Calendar.SECOND);
	    if(calendar.get(Calendar.AM_PM) == 0)
	      am_pm = "AM";
	    else
	      am_pm = "PM";
	  String time= "Current Time : " + hour + ":" + minute + " " + am_pm;
	    System.out.println(time);
	    Collator myCollator = Collator.getInstance();
	 

	      if(( myCollator.compare(time, "4.00 PM") == 0 ))
	        {
	         
	                JOptionPane.showMessageDialog(null,"Same Day Delivery is applicable for your order");
	        }else{
	        	JOptionPane.showMessageDialog(null, "Same Day Delivery is not applicable for your order!");
	        }
	    
	






        
//         
    }//GEN-LAST:event_checkTimeJButtonActionPerformed

    private void payJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderjTable.getSelectedRow();
//        if(selectedRow<0){
//        JOptionPane.showMessageDialog(null, "Select a row first");
//            return;
//        }
      //  OrderItem selectedItem =(OrderItem) orderjTable.getValueAt(selectedRow, 1);
        
        PaymentJPanel pjp = new PaymentJPanel(userProcessContainer,tempInvoice,tempOrder,customerPerson,account,system,organization);
        userProcessContainer.add("PaymentJPanel",pjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_payJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton2;
    private javax.swing.JButton checkTimeJButton;
    private javax.swing.JButton estimateSalesJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderjTable;
    private javax.swing.JButton payJButton;
    private javax.swing.JButton refreshjButton1;
    private javax.swing.JTextField taxjTextField;
    private javax.swing.JTextField tivjTextField;
    private javax.swing.JTextField totalValuejTextField;
    // End of variables declaration//GEN-END:variables
}
