/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.FinancialAccount.AmazonFinancialAccount;
import Business.FinancialAccount.SupplierFinancialAccount;
import Business.Network.Network;
import Business.Role.AdminRole;
import Business.Role.SystemAdminRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SupplierRegistrationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class ManageSupplierNetworkJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private WorkRequest request;
  
    /**
     * Creates new form ManageNetworkJPanel
     */
    public ManageSupplierNetworkJPanel(JPanel userProcessContainer, EcoSystem system, WorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.request = request;
        populateForm();
    }

    private void populateForm(){
        countryJTextField.setText(((SupplierRegistrationRequest)request).getCountryRequest());
        statejTextField.setText(((SupplierRegistrationRequest)request).getStateRequest());
        cityjTextField.setText(((SupplierRegistrationRequest)request).getCityRequest());
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        countryJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        statejTextField = new javax.swing.JTextField();
        cityjTextField = new javax.swing.JTextField();
        createSupplierAdminButton = new javax.swing.JButton();
        cancelRequestJButton = new javax.swing.JButton();

        jLabel1.setText("Country:");

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("State :");

        jLabel3.setText("City :");

        createSupplierAdminButton.setText("Create Supplier Admin");
        createSupplierAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSupplierAdminButtonActionPerformed(evt);
            }
        });

        cancelRequestJButton.setText("Cancel Request");
        cancelRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRequestJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                                .addGap(53, 53, 53))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(15, 15, 15)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(countryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statejTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cityjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createSupplierAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(cancelRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(countryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(statejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitJButton)
                    .addComponent(backJButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createSupplierAdminButton)
                    .addComponent(cancelRequestJButton))
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        
        Network network = system.getNetwork();
        System.out.println(network);
        String countryName = countryJTextField.getText();
        String stateName = statejTextField.getText();
        String cityName = cityjTextField.getText();
            
            if(!network.getNetworkList().isEmpty()){
                for(int i=0; i<network.getNetworkList().size(); i++ ){
                    Network country = network.getNetworkList().get(i);
                    if(countryName.equalsIgnoreCase(country.getName())){
                        for (int j=0; j<network.getNetworkList().size(); j++){
                            Network state = country.getNetworkList().get(j);
                                if(stateName.equalsIgnoreCase(state.getName())){
                                    for(int k=0; k<network.getNetworkList().size(); k++){
                                        Network city = state.getNetworkList().get(k);
                                            if (cityName.equalsIgnoreCase(city.getName())){
                                                JOptionPane.showMessageDialog(null, "City already exists!! Cannot create a new one");
                                                return;
                                            }else{
                                            city = state.createAndAddCity(cityName);
                                            return;
                                            }
                                    }
                                
                                }else{
                                state = country.createAndAddState(stateName);
                                Network city = state.createAndAddCity(cityName);
                                return;
                                }
                        }
                    
                    }else{
                        country = network.createAndAddCountry(countryName);
                        Network state = country.createAndAddState(stateName);
                        Network city = state.createAndAddCity(cityName);
                        return;
                    }
                }
            }else{
                Network country = network.createAndAddCountry(countryName);
                Network state = country.createAndAddState(stateName);
                Network city = state.createAndAddCity(cityName);
                return;
            
            }
          
            
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void createSupplierAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSupplierAdminButtonActionPerformed
        // TODO add your handling code here:
        
        //PersonWorkRequest request = (PersonWorkRequest) workRequestjTable.getValueAt(selectedRow, 0);
        
        
        String countryName = countryJTextField.getText();
        String stateName = statejTextField.getText();
        String cityName = cityjTextField.getText();
        
         Network network = system.getNetwork();
            
            for (Network country : network.getNetworkList()) {
            if (countryName.equalsIgnoreCase(country.getName())) {
                for (Network state : country.getNetworkList()) {
                    if (stateName.equalsIgnoreCase(state.getName())) {

                        for (Network city : state.getNetworkList()) {
                            if (cityName.equalsIgnoreCase(city.getName())) {
                                Enterprise ent = city.getEnterpriseDirectory().createAndAddEnterprise(request.getMessage(), Enterprise.EnterpriseType.Supplier);
                                ent.setEnterpriseCountry(countryName);
                                ent.setEnterpriseState(stateName);
                                ent.setEnterpriseCity(cityName);
                                

                                request.getSender().setRole(new AdminRole());
                                ent.getUserAccountDirectory().getUserAccountList().add(request.getSender());
                                for (UserAccount ua : ent.getUserAccountDirectory().getUserAccountList()) {
                                        ua.setEmployee(request.getSender().getEmployee());
                                    }
                                    ((SupplierRegistrationRequest) request).setTestResult("Approved");
                                    request.setStatus("Completed");
                                    
                                    
                                
                            }
                        }

                    }
                }
            }
        }
            
            JOptionPane.showMessageDialog(null, "A new Enterprise with Enterprise Admin has been created!");
                                               
    }//GEN-LAST:event_createSupplierAdminButtonActionPerformed

    private void cancelRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRequestJButtonActionPerformed
        // TODO add your handling code here:
        
        ((SupplierRegistrationRequest) request).setTestResult("Disapproved");
    }//GEN-LAST:event_cancelRequestJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton cancelRequestJButton;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JTextField countryJTextField;
    private javax.swing.JButton createSupplierAdminButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField statejTextField;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
